INSERT INTO cart (cartid, typecart, usercart)
VALUES
    (1, 'Shopping', 'utilisateur1'),
    (2, 'Wishlist', 'utilisateur2'),
    (3, 'Shopping', 'utilisateur3'),
    (4, 'Wishlist', 'utilisateur4'),
    (5, 'Shopping', 'utilisateur5'),
    (6, 'Wishlist', 'utilisateur6'),
    (7, 'Shopping', 'utilisateur7'),
    (8, 'Wishlist', 'utilisateur8'),
    (22, 'Shopping', 'utilisateur9'),
    (10, 'Wishlist', 'utilisateur10'),
    (11, 'Shopping', 'utilisateur11'),
    (12, 'Wishlist', 'utilisateur12'),
    (13, 'Shopping', 'utilisateur13'),
    (14, 'Wishlist', 'utilisateur14'),
    (15, 'Shopping', 'utilisateur15'),
    (16, 'Wishlist', 'utilisateur16'),
    (17, 'Shopping', 'utilisateur17'),
    (18, 'Wishlist', 'utilisateur18'),
    (19, 'Shopping', 'utilisateur19'),
    (20, 'Wishlist', 'utilisateur20');
