INSERT INTO product (productid, productname, price, stockquantity, category, categorydescription)
VALUES
    (22, 'Smartphone X', 699.99, 100, 'Electronics', 'High-end smartphones with advanced features.'),
    (2, 'Laptop Pro', 1199.99, 50, 'Electronics', 'Powerful laptop for professionals.'),
    (3, 'Cotton T-Shirt', 19.99, 200, 'Clothing', 'Comfortable cotton t-shirt for everyday wear.'),
    (4, 'Jeans Classic', 49.99, 150, 'Clothing', 'Classic denim jeans for any occasion.'),
    (5, 'Coffee Maker', 79.99, 75, 'Home and Kitchen', 'Brew your favorite coffee at home.'),
    (6, 'Non-Stick Pan', 29.99, 100, 'Home and Kitchen', 'Durable non-stick cooking pan.'),
    (7, 'Skin Care Set', 39.99, 120, 'Beauty and Personal Care', 'Complete skincare regimen.'),
    (8, 'Yoga Mat', 24.99, 90, 'Sports and Outdoors', 'High-quality yoga mat for exercise.'),
    (9, 'Mystery Novel', 14.99, 250, 'Books', 'Engaging mystery novel for readers.'),
    (10, 'Remote Control Car', 34.99, 50, 'Toys and Games', 'Fun remote control car for all ages.'),
    (11, 'Car Cleaning Kit', 29.99, 80, 'Automotive', 'Cleaning essentials for your car.'),
    (12, 'Multivitamins', 9.99, 300, 'Health and Wellness', 'Daily multivitamins for overall health.'),
    (13, 'Wireless Earbuds', 49.99, 120, 'Electronics', 'Wireless earbuds for on-the-go audio.'),
    (14, 'Summer Dress', 39.99, 80, 'Clothing', 'Light and stylish dress for summer.'),
    (15, 'Blender Pro', 89.99, 60, 'Home and Kitchen', 'Powerful blender for smoothies and more.'),
    (16, 'Football', 19.99, 40, 'Sports and Outdoors', 'Classic football for outdoor play.'),
    (17, 'Cookbook', 12.99, 180, 'Books', 'Cooking inspiration with a variety of recipes.'),
    (18, 'Building Blocks', 24.99, 70, 'Toys and Games', 'Creative building blocks for kids.'),
    (19, 'Car Seat Covers', 49.99, 100, 'Automotive', 'Protective car seat covers.'),
    (20, 'Protein Powder', 29.99, 200, 'Health and Wellness', 'High-quality protein supplement.');
