INSERT INTO review (reviewid, rating, comment)
VALUES
    (1, 5, 'Excellent product!'),
    (2, 4, 'Good value for the price.'),
    (3, 3, 'Average quality, could be better.'),
    (4, 5, 'Absolutely love it.'),
    (5, 2, 'Disappointed with the purchase.'),
    (6, 4, 'Recommended to others.'),
    (7, 3, 'Not as described.'),
    (8, 1, 'Waste of money.'),
    (9, 5, 'Surpassed my expectations.'),
    (10, 4, 'Satisfied with the product.'),
    (11, 3, 'Mixed feelings about this.'),
    (12, 5, 'Would buy again.'),
    (13, 2, 'Not worth the price.'),
    (14, 4, 'Impressive quality.'),
    (15, 3, 'Could improve in some aspects.'),
    (16, 1, 'Regretting the purchase.'),
    (17, 5, 'Great value, great quality.'),
    (18, 4, 'Met my requirements.'),
    (19, 3, 'Decent product overall.'),
    (20, 5, 'Exceeded expectations.');
