INSERT INTO users (id, username, email, work, password)
VALUES
    (1, 'utilisateur1', 'utilisateur1@email.com', 'Travail 1', 'mdp1'),
    (2, 'utilisateur2', 'utilisateur2@email.com', 'Travail 2', 'mdp2'),
    (3, 'utilisateur3', 'utilisateur3@email.com', 'Travail 3', 'mdp3'),
    (4, 'utilisateur4', 'utilisateur4@email.com', 'Travail 4', 'mdp4'),
    (5, 'utilisateur5', 'utilisateur5@email.com', 'Travail 5', 'mdp5'),
    (6, 'utilisateur6', 'utilisateur6@email.com', 'Travail 6', 'mdp6'),
    (7, 'utilisateur7', 'utilisateur7@email.com', 'Travail 7', 'mdp7'),
    (8, 'utilisateur8', 'utilisateur8@email.com', 'Travail 8', 'mdp8'),
    (9, 'utilisateur9', 'utilisateur9@email.com', 'Travail 9', 'mdp9'),
    (10, 'utilisateur10', 'utilisateur10@email.com', 'Travail 10', 'mdp10'),
    (11, 'utilisateur11', 'utilisateur11@email.com', 'Travail 11', 'mdp11'),
    (12, 'utilisateur12', 'utilisateur12@email.com', 'Travail 12', 'mdp12'),
    (13, 'utilisateur13', 'utilisateur13@email.com', 'Travail 13', 'mdp13'),
    (14, 'utilisateur14', 'utilisateur14@email.com', 'Travail 14', 'mdp14'),
    (15, 'utilisateur15', 'utilisateur15@email.com', 'Travail 15', 'mdp15'),
    (16, 'utilisateur16', 'utilisateur16@email.com', 'Travail 16', 'mdp16'),
    (17, 'utilisateur17', 'utilisateur17@email.com', 'Travail 17', 'mdp17'),
    (18, 'utilisateur18', 'utilisateur18@email.com', 'Travail 18', 'mdp18'),
    (19, 'utilisateur19', 'utilisateur19@email.com', 'Travail 19', 'mdp19'),
    (20, 'utilisateur20', 'utilisateur20@email.com', 'Travail 20', 'mdp20');
